---
- name: Change site
  hosts: all
  become: true
  vars_files:
    - /home/user/task/DVPS-ANS-07/products.yaml
    
  tasks:
    - name: Update packeges and install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Add nginx to autostart
      ansible.builtin.service:
        name: nginx
        enabled: yes

    - name: Copy config to server nginx
      ansible.builtin.copy:
        src: /home/user/task/DVPS-ANS-07/nginx.conf
        dest: /etc/nginx/nginx.conf
        notify: reload nginx

    - name: Delete default site and default html
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop:
        - { path: "/etc/nginx/sites-enabled/default" }
        - { path: "/var/www/html/index.nginx-debian.html" }

    - name: Add config site
      ansible.builtin.template:
        src: /home/user/task/DVPS-ANS-07/site.conf.j2
        dest: /etc/nginx/sites-available/site.conf
        notify: reload nginx

    - name: Create symbolic link to web-site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/site.conf
        dest: /etc/nginx/sites-enabled/site.conf
        state: link

    - name: Create static html for products
      ansible.builtin.template:
        src: /home/user/task/pages_html.j2
        dest: /home/user/task/{{ item.name | lower }}.html
      loop: "{{ products }}"

    - name: Find html files
      ansible.builtin.find:
        paths: "/home/user/task/"
        patterns: "*.html"
      register: found_files
      
    - name: Copy html to server
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: "/var/www/html/"
      loop: "{{ found_files.files }}"

    - name: Create main html for products
      ansible.builtin.template:
        src: /home/user/task/main_html.j2
        dest: /home/user/task/{{ item.name | lower }}.html
      loop: "{{ products }}"

  handlers:
    - name: reload nginx
      ansible.builtin.service:
        name: nginx
        state: reload
